framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\Message\SendChannelMessage: async
            App\Message\CreateNewsMessage: async